server:
  port: 8033
web:
  domain: http://localhost
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: xigongda123
    url: jdbc:mysql://localhost:3306/crowdos_community?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    type: com.zaxxer.hikari.HikariDataSource



logging:
  level:
    root: info
    com.crowdos.crowdos_community_backend: info