server:
  port: 8033
  tomcat:
    relaxed-query-chars: "[,]"
web:
  domain: http://localhost
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: xigongda123
    url: jdbc:mysql://localhost:3306/crowdos_community?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    type: com.zaxxer.hikari.HikariDataSource
  thymeleaf:
    cache: false
  redis:
    database: 0
    host: localhost
    port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: community-consumer-group
      enable-auto-commit: true #自动提交
      auto-commit-interval: 3000 #3000ms提交一次
  elasticsearch:
    rest:
      uris: localhost:9200
      connection-timeout: 1s
      read-timeout: 30s


logging:
  level:
    root: info
    com.crowdos.crowdos_community_backend: debug

